### ISSUE TITLE
App version is not captured 

### ISSUE THREAD

**Issue by maniveltvl** [Tealium/tealium-flutter#37] opened 2023-08-25 12:56 UTC
Hi, Team

We are using the tealium version 2.4.0, but Adobe Tealium dashboard is not captured app version. Please find the below config that we are using in app.

`Tealium.initialize(TealiumConfig(
      Constants.tealium_account,
      Constants.tealium_profile,
      env == 'prod' ? TealiumEnvironment.prod : TealiumEnvironment.dev,
      [Collectors.AppData, Collectors.Lifecycle],
      [Dispatchers.RemoteCommands, Dispatchers.Collect],
      consentPolicy: ConsentPolicy.GDPR,
      useRemoteLibrarySettings: true,
      batchingEnabled: false,
      visitorServiceEnabled: true,
      consentExpiry: ConsentExpiry(1, TimeUnit.MINUTES),
    )`

Please advise us if any issue in configuration.

**Comment by craigrouse** [comment] 2023-08-25 13:01
Hi @maniveltvl. Those settings look fine. Are you sure that `app_version` is mapped in your Tealium profile to a variable in your Adobe Analytics connector? For more personal support, please contact support@tealium.com, and a colleague will be able to check your configuration properly for you.

**Comment by craigrouse** [comment] 2023-08-25 13:12
One other comment: I just ran the sample app using version 2.4.0 of the Tealium Flutter plugin, and I can see app_version being sent from the device correctly, so I would say this is almost certainly a configuration issue in your Tealium profile.

**Comment by maniveltvl** [comment] 2023-08-29 15:56
Hi, @craigrouse 

We just checked the Tealium data flow between app and Tealium, we could see the connection to app in Charles proxy app, it is not picking up the data layer. we could see tags.tiqcdn.com/utag and connect.tealiumiq.com/event, but app is not able to access the data layer and Tealium cannot therefore run the iQ config and build / fire the AA server call. 

Do we need add anything in app config side?

**Comment by jameskeith** [comment] 2023-08-30 14:24
@maniveltvl - Is it possible to provide the account/profile that is used in the above example? if not, then could it be provided to our Support team at support@tealium.com ?

From the example configuration you have provided in the initial issue, the `Dispatchers.TagManagement` dispatcher is not included, which would certainly stop IQ from being initialised within the SDK. At the moment, it's unclear to me whether this is expected to be sent from our IQ product or from EventStream and without knowing which products you have configured Adobe Analytics in, I couldn't say for certain what the issue might be.
The account and profile would probably help to narrow down the cause and also potentially help us reproduce the issue for troubleshooting purposes.

**Comment by maniveltvl** [comment] 2023-08-31 08:46
Hi @jameskeith 

Thanks for your reply. Our account and profile was working when we use thallium package 1.2.0. After upgrade our Flutter framework from 1.x to 3.x and upgrade thallium package 2.4.0, it stopped working. We have raised ticket to thallium support team (#228886). Meanwhile we will try to add `Dispatchers.TagManagement` and check. We are waiting for support team response. This issue is very critical to us.

**Comment by jameskeith** [comment] 2023-08-31 10:14
@maniveltvl 
Thanks for the information - The change from v1 -> v2 of our Flutter integration migrated from using legacy native SDKs (obj-c + Java) to our newer Swift/Kotlin SDKs. As such the increased modularity has changed the configuration quite a bit.

Looking at the account/profile in your support ticket, I would suggest that your config is _not correct_. 
I can see that you rely on Tealium IQ for the Adobe Analytics. As a result, you will definitely need the `Dispatchers.TagManagement` module added to your configuration.

It would also be recommended to review the Dispatchers that you have in your config - if you don't need/use them, then they  should be removed:
 - `Dispatchers.Collect` is for sending events to our server side products, but without the need of the WebView required by the TagManagement module. Adding this dispatcher is essentially equivalent to adding the Tealium Collect tag into your IQ profile. If left enabled, then you should ensure there is a valid contract in place for the event volume.
 - `Dispatchers.RemoteCommands` is for interfacing with any Remote Command implementations that your app may make use of - if you don't have any, then you probably won't need this module.
 - `Dispatchers.TagManagement` is for running a Tealium IQ profile in your app, supporting the tags that you have added to the configured profile.
 
 Hopefully that helps.

**Comment by jameskeith** [comment] 2023-09-01 13:06
@maniveltvl 
I hope all is going well at your end - I have a couple of things to consider in addition to what's already mentioned:
 - There was also a known issue with the our Swift SDK migrating old app versions that was resolved in the very [latest release](https://github.com/Tealium/tealium-swift/releases/tag/2.10.1) so you should ensure that your Pods are up to date for your iOS release
 - It may just be a configuration option for testing purposes, but setting ConsentExpiry to 1 or 5 minutes is unusual in my experience; was this just for testing or was there a good use case?

**Comment by maniveltvl** [comment] 2023-09-07 09:58
Hi @jameskeith 

Thanks for your help. After updating Dispatchers in config, it started working now.

What is your suggestion on ConsentExpriy value? Right now we are keeping 60 minutes.

**Comment by jameskeith** [comment] 2023-09-07 10:15
@maniveltvl thanks for confirming; glad to hear it's all working as expected.

> Is this included in latest Flutter Tealium package?
It will be, but only if the build machine has the latest set of CocoaPods pods at the time of building the application, using the `pod update` command. 

> What is your suggestion on ConsentExpriy value? Right now we are keeping 60 minutes.

That's up to yourselves to choose I'm afraid. The setting is available to allow customisation around how often a user needs to re-consent to any event data being sent. So this is largely up to any jurisdiction that may have enforced the consent requirements. So whilst I can't speak for your specific case - it's quite unusual to have to re-consent every 1 or 5 minutes unless it's specifically for testing, so I thought I'd point it out.

**Closed** 2023-09-15 16:48 UTC
